M48
; DRILL file {KiCad 7.0.9} date Friday, January 12, 2024 at 07:02:31 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-12T19:02:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0390
%
G90
G05
T2
X-0.4686Y-0.2598
T3
X-0.3826Y-0.6175
X-0.1939Y-0.5401
X-0.1787Y-0.6186
T1
G00X-0.2653Y-0.463
M15
G01X-0.2542Y-0.4741
M16
G05
T0
M30
